# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Workrs
User.create(password: "123456", email: "pete@pete.com", name: "Pete", address: "Kensington, England, United Kingdom", area_of_influence: 20, rate: 350, skill: "Elevator Installer", about_me: "I am a fully qualified, experienced electrician th...", certificates: "Level 3 NVQ diploma in Installing Electrotechnical...", experience: "Lorem ipsum dolor sit amet, qui ea odio virtute, m...", photo: "image/upload/v1542974749/wtru5dzdu4qmsd0nfanu.jpg", latitude: 51.4989948, longitude: -0.1991229, company: false)
User.create(password: "123456", email: "pedrovl@pedrovl.com", name: "Pedro", address: "Putney Vale, London Borough of Wandsworth, England...", area_of_influence: 30, rate: 300, skill: "Electrical Engineering Technician", about_me: "Fully qualified and highly experienced in electric...", certificates: "NVQ diploma level 12", experience: "Lorem ipsum dolor sit amet, qui ea odio virtute, m...", photo: "image/upload/v1542977314/ehwbeifdu2smhrlwrsfi.jpg", latitude: 51.4380193, longitude: -0.2459701, company: false)
User.create(password: "123456", email: "kristian@kristian.com", name: "Krisitan", address: "Radlett, England, United Kingdom", area_of_influence: 30, rate: 300, skill: "Electrician solar photovoltaic specialist", about_me: "Fully qualified and highly experienced in the inst...", certificates: "GNVQ level 12", experience: "Lorem ipsum dolor sit amet, qui ea odio virtute, m...", photo: "image/upload/v1542977653/td2vjarzwrexqoq06m8n.jpg", latitude: 51.6843112, longitude: -0.3175279, company: false)
User.create(password: "123456", email: "youseff@youseff.com", name: "Youseff", address: "Chessington, Royal Borough of Kingston upon Thames...", area_of_influence: 40, rate: 350, skill: "Electrical Engineering Line Install Technician", about_me: "Highly experienced and fully qualified in new infr...", certificates: "GNVQ level 12", experience: "Lorem ipsum dolor sit amet, qui ea odio virtute, m...", photo: "image/upload/v1542977953/drgxgpxxzd8t0knxwurp.jpg", latitude: 51.358336, longitude: -0.2986216, company: false)
# Companies
User.create(password: "123456", email: "kiergroup@kiergroup.com", name: "Kier Group", address: "6 Cavendish Street, London Borough of Hackney, Eng...", area_of_influence: 300, rate: 100000000, skill: "Government Contracts", about_me: "Kier Group plc is a UK construction, services and ...", certificates: "Government approved", experience: "Founded in 1928\r\n\r\nLorem ipsum dolor sit amet, qui...", photo: "image/upload/v1542975636/kkkvfdx81zvc2ysiebpp.png", latitude: 51.532674, longitude: -0.0879977, company: true)
User.create(password: "123456", email: "balfourbeatty@balfourbeatty.com", name: "Balfour Beatty", address: "5 Churchill Place, London Borough of Tower Hamlets...", area_of_influence: 400, rate: 100000000, skill: "Government Contracts", about_me: "Balfour Beatty plc is a UK-based multinational inf...", certificates: "Government approved", experience: "1909 by George Balfour and Andrew Beatty\r\n\r\nLorem ...", photo: "image/upload/v1542976115/hkfotffzwohhtpkunlhu.png", latitude: 51.5046506, longitude: -0.0135141880533771, company: true)
User.create(password: "123456", email: "laing@laing.com", name: "Laing O'Rourke", address: "Victoria Dock Road, London Borough of Newham, Engl...", area_of_influence: 300, rate: 10000000, skill: "Government Contracts", about_me: "Laing O'Rourke is a multinational construction com...", certificates: "Government approved", experience: "Founded in 1978 by Ray O'Rourke.\r\n\r\nLorem ipsum do...", photo: "image/upload/v1542976605/u8dxqslzl3oe8ylm2brr.png", latitude: 51.5091558, longitude: 0.0157921, company: true)
